FROM node:8
ENV NODE_ENV=production
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN npm -g config set user root
RUN npm install -g serve
COPY build/ .
EXPOSE 4000
CMD [ "serve", "-l", "4000", "-s", "./", "-n" ]
